name: Deploy to MVN

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MVN_DEPLOY_KEY }}

      - name: Checkout MVN repository
        uses: actions/checkout@v4
        with:
          repository: ReflectionMC/mvn.reflection.ghosty.im
          ref: main
          path: deploy-repo
          fetch-depth: '1'
          ssh-key: ${{ secrets.MVN_DEPLOY_KEY }}

      - name: Publish
        run: ./gradlew publish -PdeployRepoPath="$PWD/deploy-repo"

      - name: Commit and push
        run: |
          cd deploy-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add new build from $GITHUB_REPOSITORY@$GITHUB_SHA (run #${GITHUB_RUN_NUMBER})"
          git push